[project]
name = "terminal-note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
