[project]
name = "terminal-note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pylint>=3.3.7",
    "textual>=3.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.12",
]
