[mode]
# Пока не работает, добавил чтобы не забыть
storage_mode = "files" # Data storage mode either in SQL or in JSON file or ordinary files, Data storage mode either in SQL or in JSON file or regular files

[backend]
path_to_storage_directory = "$HOME/terminal_note"
file_extension = "md"
file_reader = "bat" # bat, cat, less

[template]
path_to_template_note = "$HOME/terminal_note/templates/template.md"

[editor]
editor = "nvim"
