name: Publish Python package to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write 

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # нужная версия Python

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip build

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
